name: leonardo_mobile
description: A minimal Flutter client for Leonardo (Android)
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.7
  http: ^0.13.6
  shared_preferences: ^2.1.4
  google_sign_in: ^6.0.0
  webview_flutter: ^4.10.0
  markdown: ^7.3.1
  url_launcher: ^6.3.1
  file_picker: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/iris_logo.png
